id: I3633E069
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T17:52:46+00:00'
last_modified: '2022-06-08T13:27:32.756819+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1016286
  title: སྒོམ་གྱི་གནད་གསལ་བར་ཕྱེ་བ་བསམ་གཏན་མིག་སྒྲོན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    65B5:
      image_group_id: I00JW501191
      title: ''
      total_pages: 518
      order: 1
      base_file: 65B5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
