id: P010418
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1016286
  title: སྒོམ་གྱི་གནད་གསལ་བར་ཕྱེ་བ་བསམ་གཏན་མིག་སྒྲོན།
  author: ''
  volumes:
    cc2e41f4634d4fb4a7da07e123c66cd9:
      image_group_id: I00JW501191
      title: ''
      volume_number: 1
      total_pages: 518
